<a href="https://colab.research.google.com/github/19pa1a0456/ai/blob/master/tony.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
a=12
b=34
if (a>b):
  print(a)
else:
  print(b)

34


In [16]:
r=int(input())
for i in range(1,r+1):
  if i%2==0:
    print(i)
  

99
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98


In [17]:
import numpy as np
t=np.array([1,2,3,4])
print(t)

[1 2 3 4]


In [18]:
import numpy as np
x=np.linspace(start=1,stop=5)
print(x)

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


In [19]:
import numpy as np
x=np.arange(start=1,stop=20,step=2)
print(x)

[ 1  3  5  7  9 11 13 15 17 19]


In [20]:
import numpy as np
x=np.ones((3,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
import numpy as np
x=np.zeros((3,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
import numpy as np
x=np.random.rand(2,5)
print(x)

[[0.35431331 0.84011687 0.80272889 0.40666876 0.31884901]
 [0.36676963 0.47823515 0.84692047 0.27106489 0.68774186]]
